// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogihrnxtsafuegosuujm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9naWhybnh0c2FmdWVnb3N1dWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjM4NzgsImV4cCI6MjA2OTA5OTg3OH0.140qV6th0v6UJ1f1EHTKhcjioc77tA5ccr9ZghKr41Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});